import os
import sys
import glob
import numpy as np
import pandas as pd
import math
import sys
import random
import pickle

import dask.dataframe as dd
from dask.distributed import Client

import torch
import pyro
import pyro.distributions as dist
import pyro.distributions.constraints as constraints
from pyro.nn import PyroModule

from tqdm import tqdm
from torch.utils.data import Dataset, DataLoader

sys.path.insert(0, '/home/djl34/lab_pd/kl/git/KL')
import raklette_updated

sys.path.insert(0, '/home/djl34/lab_pd/kl/git/KL/noncoding_analysis/kl_gene')
from raklette_gene import run_raklette


KL_data_dir = "/home/djl34/lab_pd/kl/data"
scratch_dir = "/n/scratch3/users/d/djl34"

base_set = ["A", "C", "T", "G"]
chrom_set = [str(x) for x in range(1, 23)]
# chrom_set = ["22"]


gene_set_file = os.path.join(scratch_dir, "kl_input/enhancer_module/unique_gene.tsv")

if os.path.isfile(gene_set_file):
    df = pd.read_csv(os.path.join(scratch_dir, "kl_input/enhancer_module/unique_gene.tsv"), sep = "\t", header = None)
    gene_set = df[0]
else:
    gene_set = []
    
# gene_set = [0]

rule all:
    input:
        [os.path.join(scratch_dir, "kl_input/enhancer_module/" + chrom +".tsv") for chrom in chrom_set],
        gene_set_file,
        [os.path.join(scratch_dir, "kl_input/enhancer_module/divided/gene_" + str(gene) +".tsv") for gene in gene_set],
        os.path.join(scratch_dir, "kl_input/enhancer_module/gene.tsv"),
        os.path.join(KL_data_dir, "raklette_output/kl_gene/enhancer_module/all_noncoding.tsv")

        
########################### filter sites for KL analysis ###########################

rule make_tsv_files:
    input:
        os.path.join(scratch_dir, "whole_genome/enhancer/{chrom}/_metadata")
    output:
        os.path.join(scratch_dir, "kl_input/enhancer_module/{chrom}.tsv")
    run:
        with Client() as client:
            
            rate = dd.read_parquet("/".join(input[0].split("/")[:-1]) + "/")
            
            print(rate.columns)
            
            rate = rate[rate["coding"] == False]
             
            rate["e_module"] = rate["e_module"].fillna(-1)
            rate["e_module"] = rate["e_module"].astype(int)
            include_columns = ["mu_index", "Freq_bin", "e_module"]
            
            rate = rate[include_columns]
            
            rate.to_csv(output[0], sep = "\t", index = None, single_file = True)

rule get_unique_genes:
    input:
        [os.path.join(scratch_dir, "kl_input/enhancer_module/" + chrom +".tsv") for chrom in chrom_set]
    output:
        os.path.join(scratch_dir, "kl_input/enhancer_module/unique_gene.tsv")
    run:
        with Client() as client:
            rate = dd.read_csv("/".join(input[0].split("/")[:-1]) + "/" + "*.tsv", sep = "\t", 
                               dtype={'e_module': 'int'})
            
            minimum_value = rate["e_module"].min().compute()
            print(minimum_value)
            maximum_value = rate["e_module"].max().compute()
            print(maximum_value)
            
            f = open(output[0], "a")
            
            for i in range(minimum_value, maximum_value + 1):
                f.write(str(i) + "\n")
            
            f.close()
        
        
rule divide_by_gene_tsv_files:
    input:
        [os.path.join(scratch_dir, "kl_input/enhancer_module/" + chrom +".tsv") for chrom in chrom_set]
    output:
        os.path.join(scratch_dir, "kl_input/enhancer_module/divided/gene_{gene}.tsv")
    run:
        with Client() as client:
            rate = dd.read_csv([os.path.join(scratch_dir, "kl_input/enhancer_module/" + chrom +".tsv") for chrom in chrom_set], sep = "\t", dtype={'e_module': 'int'})
            
            rate_gene = rate[rate["e_module"] == int(wildcards.gene)]
            
            rate_gene.to_csv(output[0], sep = "\t", index = None, single_file = True)
            
rule merge_tsv_files:
    input:
        [os.path.join(scratch_dir, "kl_input/enhancer_module/divided/gene_" + str(gene) +".tsv") for gene in gene_set]
    output:
        os.path.join(scratch_dir, "kl_input/enhancer_module/gene.tsv")
    run:
        with Client() as client:
            rate = dd.read_csv([os.path.join(scratch_dir, "kl_input/enhancer_module/divided/gene_" + str(gene) +".tsv") for gene in gene_set], sep = "\t", dtype={'e_module': 'int'})
            
            rate.to_csv(output[0], sep = "\t", index = None, single_file = True)
                
# ##################### For running KL analysis #############################
        
rule run_KL_enhancer_module:
    input:
        variants = os.path.join(scratch_dir, "kl_input/enhancer_module/gene.tsv"),
        neutral_sfs = KL_data_dir + "/neutral_SFS_5bins.tsv"
    output:
        os.path.join(KL_data_dir, "raklette_output/kl_gene/enhancer_module/all_noncoding.tsv")
    run:
        class TSVDataset(Dataset):
            def __init__(self, path, chunksize, nb_samples, header_all, features):
                self.path = path
                self.chunksize = chunksize
                self.len = nb_samples // self.chunksize
                self.header = header_all
                self.features = features

            def __getitem__(self, index):
                x = next(
                    pd.read_csv(
                        self.path,
                        sep = "\t",
                        skiprows=index * self.chunksize + 1,  #+1, since we skip the header
                        chunksize=self.chunksize,
                        names=self.header))

                x = x[self.features]
                x["e_module"] = x["e_module"] + 1
                x = torch.from_numpy(x.values)
                return x

            def __len__(self):
                return self.len
            
        input_filename = input.variants
        output_filename = output[0]
        neutral_sfs_filename = input.neutral_sfs
        
        with Client() as client:
            df = dd.read_csv(input_filename, sep = "\t")
            nb_samples = len(df)
            header = df.columns
            n_genes = len(df["e_module"].unique()) + 1
            del df
            print("done reading")
            
        chunksize = 100000
        dataset = TSVDataset(input_filename, chunksize=chunksize, nb_samples = nb_samples, header_all = header, features = header)
        
        print("number of chunks " + str(nb_samples/chunksize))

        loader = DataLoader(dataset, batch_size=10, num_workers=1, shuffle=False)
        
        n_covs = 0
        num_epochs = 1
        
        run_raklette(loader, n_covs, n_genes, num_epochs, neutral_sfs_filename, output_filename)
        
        
            
        